import * as React from 'react';
import { ClipboardDocumentCheckIcon, ClipboardDocumentIcon, ServerIcon, ShieldCheckIcon, ExclamationTriangleIcon } from './icons';

// Helper component for copying text (Internal)
const CopyButton: React.FC<{ textToCopy: string }> = ({ textToCopy }) => {
    const [copied, setCopied] = React.useState(false);
    const handleCopy = () => {
        navigator.clipboard.writeText(textToCopy).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };
    return (
        <button type="button" onClick={handleCopy} className="flex items-center gap-1 px-3 py-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 rounded transition-colors shadow-sm" title="نسخ الكود">
            {copied ? <ClipboardDocumentCheckIcon className="w-4 h-4 text-white" /> : <ClipboardDocumentIcon className="w-4 h-4" />}
            {copied ? 'تم النسخ!' : 'نسخ كود SQL'}
        </button>
    );
};

const unifiedScript = `
-- =================================================================
-- السكربت الشامل لإصلاح وإعداد قاعدة البيانات (النسخة 1.5.2)
-- حل مشكلة "infinite recursion detected" وإصلاح خطأ عمود role
-- =================================================================

-- 1. إعداد جدول الملفات الشخصية (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (id uuid NOT NULL PRIMARY KEY);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mobile_number text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_approved boolean DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mobile_verified boolean DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS otp_code text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS otp_expires_at timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_start_date date;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS subscription_end_date date;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role text DEFAULT 'user';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS lawyer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS permissions jsonb DEFAULT '{}';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_profiles_mobile_number ON public.profiles(mobile_number);

-- 2. الدوال المساعدة (تحسين للأداء والموثوقية)
CREATE OR REPLACE FUNCTION public.get_data_owner_id()
RETURNS uuid AS $$
DECLARE
    current_lawyer_id uuid;
BEGIN
    -- جلب معرف المحامي المرتبط بالمستخدم الحالي من جدول البروفايلات
    -- ملاحظة: استخدام LIMIT 1 لتجنب أي مشاكل في حال وجود سجلات مكررة
    SELECT lawyer_id INTO current_lawyer_id FROM public.profiles WHERE id = auth.uid() LIMIT 1;
    -- إذا كان المستخدم مساعداً، نرجع معرف المحامي، وإلا نرجع معرف المستخدم نفسه
    RETURN COALESCE(current_lawyer_id, auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
    -- فحص مباشر وبسيط لتجنب الاستدعاءات المتداخلة
    RETURN EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;

-- 3. الجداول الأساسية
CREATE TABLE IF NOT EXISTS public.assistants (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL, name text NOT NULL, updated_at timestamptz DEFAULT now());
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assistants_user_id_name_key') THEN ALTER TABLE public.assistants ADD CONSTRAINT assistants_user_id_name_key UNIQUE (user_id, name); END IF; END $$;

CREATE TABLE IF NOT EXISTS public.clients (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, name text NOT NULL, contact_info text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.cases (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, client_id text NOT NULL, subject text NOT NULL, client_name text, opponent_name text, fee_agreement text, status text DEFAULT 'active', updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.stages (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, case_id text NOT NULL, court text NOT NULL, case_number text, first_session_date timestamptz, decision_date timestamptz, decision_number text, decision_summary text, decision_notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sessions (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, stage_id text NOT NULL, court text, case_number text, date timestamptz NOT NULL, client_name text, opponent_name text, postponement_reason text, next_postponement_reason text, is_postponed boolean DEFAULT false, next_session_date timestamptz, assignee text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.admin_tasks (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, task text NOT NULL, due_date timestamptz NOT NULL, completed boolean DEFAULT false, importance text DEFAULT 'normal', assignee text, location text, order_index integer, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.appointments (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, title text NOT NULL, "time" text, date timestamptz NOT NULL, importance text, notified boolean, reminder_time_in_minutes integer, assignee text, completed boolean DEFAULT false, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.accounting_entries (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, type text NOT NULL, amount real NOT NULL, date timestamptz NOT NULL, description text, client_id text, case_id text, client_name text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.invoices (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, client_id text NOT NULL, client_name text, case_id text, case_subject text, issue_date timestamptz NOT NULL, due_date timestamptz NOT NULL, tax_rate real DEFAULT 0, discount real DEFAULT 0, status text DEFAULT 'draft', notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.invoice_items (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, invoice_id text NOT NULL, description text NOT NULL, amount real NOT NULL, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.site_finances (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid, type text DEFAULT 'income', payment_date date NOT NULL, amount real NOT NULL, description text, payment_method text, category text, profile_full_name text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.case_documents (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, case_id text NOT NULL, name text NOT NULL, type text NOT NULL, size real NOT NULL, added_at timestamptz DEFAULT now() NOT NULL, storage_path text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sync_deletions (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, table_name text NOT NULL, record_id text NOT NULL, user_id uuid NOT NULL, deleted_at timestamptz DEFAULT now());

-- 4. سياسات الأمان (RLS) - النسخة المصححة لتجنب التكرار اللانهائي
DO $$
DECLARE r RECORD;
BEGIN
    -- حذف جميع السياسات القديمة لضمان نظافة البيئة
    FOR r IN (SELECT 'DROP POLICY IF EXISTS "' || policyname || '" ON public.' || tablename || ';' as statement FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE r.statement;
    END LOOP;
END$$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- السياسة الذهبية لتجنب التكرار: السماح لأي مستخدم مسجل بقراءة الملفات دون شروط معقدة
CREATE POLICY "Profiles View All" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
-- التحديث مسموح فقط لصاحب الحساب أو المدير (يستخدم دالة is_admin التي صممت لتكون آمنة)
CREATE POLICY "Profiles Update Owner" ON public.profiles FOR UPDATE USING (auth.uid() = id OR public.is_admin());
-- الإدراج مسموح فقط عند إنشاء الحساب
CREATE POLICY "Profiles Insert Owner" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id OR public.is_admin());

-- سياسات جداول البيانات الأخرى (المزامنة والـ UPSERT)
DO $$
DECLARE
    t text;
    target_tables text[] := ARRAY['assistants', 'clients', 'cases', 'stages', 'sessions', 'admin_tasks', 'appointments', 'accounting_entries', 'invoices', 'invoice_items', 'case_documents', 'sync_deletions'];
BEGIN
    FOR t IN SELECT unnest(target_tables) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        -- سياسة شاملة تسمح بالوصول بناءً على معرف المحامي (المالك الأصلي للبيانات)
        EXECUTE format('CREATE POLICY "Data Access %s" ON public.%I FOR ALL USING (user_id = public.get_data_owner_id() OR public.is_admin()) WITH CHECK (user_id = public.get_data_owner_id() OR public.is_admin())', t, t);
    END LOOP;
END $$;

ALTER TABLE public.site_finances ENABLE ROW LEVEL SECURITY;
-- إصلاح خطأ عمود role المفقود في جدول site_finances عبر استخدام دالة is_admin الموثوقة
CREATE POLICY "Admins manage finances" ON public.site_finances FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
`;

interface ConfigurationModalProps {
    onRetry: () => void;
}

const ConfigurationModal: React.FC<ConfigurationModalProps> = ({ onRetry }) => {
    return (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-[200]">
            <div className="bg-white p-6 rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col">
                <div className="flex items-center gap-3 mb-4 text-amber-600">
                    <ServerIcon className="w-8 h-8" />
                    <h2 className="text-2xl font-bold">تحديث سياسات الوصول (v1.5.2)</h2>
                </div>
                
                <div className="overflow-y-auto flex-grow pr-2">
                    <div className="bg-blue-50 border-s-4 border-blue-500 p-4 mb-4 rounded text-right">
                        <p className="text-sm text-blue-700 font-bold">
                            تم إصلاح خطأ "column role does not exist" (v1.5.2). يرجى تحديث الكود في Supabase لحل مشكلة تعليق المزامنة بشكل نهائي:
                        </p>
                    </div>

                    <ol className="list-decimal list-inside space-y-4 text-sm text-gray-600 mb-6 text-right">
                        <li className="bg-gray-50 p-3 rounded-lg border border-gray-200">
                            <div className="flex justify-between items-center mb-2">
                                <CopyButton textToCopy={unifiedScript} />
                                <strong className="text-gray-900">انسخ الكود المحدث (v1.5.2):</strong>
                            </div>
                            <div className="relative">
                                <pre className="bg-gray-800 text-green-400 p-3 rounded border border-gray-700 overflow-x-auto text-xs font-mono h-32" dir="ltr">
                                    {unifiedScript}
                                </pre>
                            </div>
                        </li>
                        <li>اذهب إلى <a href="https://supabase.com/dashboard" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline font-bold">SQL Editor في Supabase</a>.</li>
                        <li>الصق الكود واضغط <strong>Run</strong>.</li>
                        <li>بعد نجاح التنفيذ، عد إلى هنا واضغط "إعادة المحاولة".</li>
                    </ol>
                </div>

                <div className="mt-6 flex justify-end pt-4 border-t">
                    <button onClick={onRetry} className="px-6 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors shadow-md">إعادة المحاولة</button>
                </div>
            </div>
        </div>
    );
};

export default ConfigurationModal;