
import * as React from 'react';
import { ClipboardDocumentCheckIcon, ClipboardDocumentIcon, ServerIcon, ShieldCheckIcon, ExclamationTriangleIcon } from './icons';

const CopyButton: React.FC<{ textToCopy: string }> = ({ textToCopy }) => {
    const [copied, setCopied] = React.useState(false);
    const handleCopy = () => {
        navigator.clipboard.writeText(textToCopy).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };
    return (
        <button type="button" onClick={handleCopy} className="flex items-center gap-1 px-3 py-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 rounded transition-colors shadow-sm" title="نسخ الكود">
            {copied ? <ClipboardDocumentCheckIcon className="w-4 h-4 text-white" /> : <ClipboardDocumentIcon className="w-4 h-4" />}
            {copied ? 'تم النسخ!' : 'نسخ كود SQL'}
        </button>
    );
};

const unifiedScript = `
-- =================================================================
-- السكربت الشامل لإصلاح وإعداد قاعدة البيانات (إصدار المزامنة المحسن)
-- =================================================================

-- 1. جدول الملفات الشخصية
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY,
    full_name text,
    mobile_number text,
    is_approved boolean DEFAULT false,
    is_active boolean DEFAULT true,
    mobile_verified boolean DEFAULT false,
    otp_code text,
    otp_expires_at timestamptz,
    subscription_start_date date,
    subscription_end_date date,
    role text DEFAULT 'user',
    lawyer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    permissions jsonb DEFAULT '{}',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 2. دوال الصلاحيات والمالك
CREATE OR REPLACE FUNCTION public.get_data_owner_id()
RETURNS uuid AS $$
DECLARE
    current_lawyer_id uuid;
BEGIN
    SELECT lawyer_id INTO current_lawyer_id FROM public.profiles WHERE id = auth.uid();
    IF current_lawyer_id IS NOT NULL THEN
        RETURN current_lawyer_id;
    ELSE
        RETURN auth.uid();
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. جداول البيانات الأساسية
CREATE TABLE IF NOT EXISTS public.assistants (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL, name text NOT NULL, CONSTRAINT assistants_unique UNIQUE(user_id, name));
CREATE TABLE IF NOT EXISTS public.clients (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, name text NOT NULL, contact_info text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.cases (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, client_id text NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE, subject text NOT NULL, client_name text, opponent_name text, fee_agreement text, status text DEFAULT 'active', updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.stages (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, case_id text NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE, court text NOT NULL, case_number text, first_session_date timestamptz, decision_date timestamptz, decision_number text, decision_summary text, decision_notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sessions (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, stage_id text NOT NULL REFERENCES public.stages(id) ON DELETE CASCADE, court text, case_number text, date timestamptz NOT NULL, client_name text, opponent_name text, postponement_reason text, next_postponement_reason text, is_postponed boolean DEFAULT false, next_session_date timestamptz, assignee text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.admin_tasks (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, task text NOT NULL, due_date timestamptz NOT NULL, completed boolean DEFAULT false, importance text DEFAULT 'normal', assignee text, location text, order_index integer, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.appointments (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, title text NOT NULL, "time" text, date timestamptz NOT NULL, importance text, notified boolean, reminder_time_in_minutes integer, assignee text, completed boolean DEFAULT false, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.accounting_entries (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, type text NOT NULL, amount real NOT NULL, date timestamptz NOT NULL, description text, client_id text, case_id text, client_name text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.invoices (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, client_id text NOT NULL, client_name text, case_id text, case_subject text, issue_date timestamptz NOT NULL, due_date timestamptz NOT NULL, tax_rate real DEFAULT 0, discount real DEFAULT 0, status text DEFAULT 'draft', notes text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.invoice_items (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, invoice_id text NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE, description text NOT NULL, amount real NOT NULL, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.site_finances (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid, type text DEFAULT 'income', payment_date date NOT NULL, amount real NOT NULL, description text, payment_method text, category text, profile_full_name text, updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.case_documents (id text NOT NULL PRIMARY KEY, user_id uuid NOT NULL, case_id text NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE, name text NOT NULL, type text NOT NULL, size real NOT NULL, added_at timestamptz DEFAULT now(), storage_path text, updated_at timestamptz DEFAULT now());

CREATE TABLE IF NOT EXISTS public.sync_deletions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name text NOT NULL,
    record_id text NOT NULL,
    user_id uuid NOT NULL,
    deleted_at timestamptz DEFAULT now()
);

-- 4. تفعيل وسياسات RLS المحسنة
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_deletions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounting_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assistants ENABLE ROW LEVEL SECURITY;

-- سياسة عامة تسمح للمالك والمساعدين بالوصول للبيانات
DO $$
DECLARE
    tbl text;
    target_tables text[] := ARRAY['clients', 'cases', 'stages', 'sessions', 'admin_tasks', 'appointments', 'accounting_entries', 'invoices', 'invoice_items', 'case_documents', 'assistants', 'sync_deletions'];
BEGIN
    FOR tbl IN SELECT unnest(target_tables) LOOP
        EXECUTE 'DROP POLICY IF EXISTS "Access Policy" ON public.' || tbl;
        EXECUTE 'CREATE POLICY "Access Policy" ON public.' || tbl || ' FOR ALL USING (user_id = public.get_data_owner_id() OR public.is_admin()) WITH CHECK (user_id = public.get_data_owner_id() OR public.is_admin())';
    END LOOP;
END $$;

-- 5. تفعيل Realtime
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY['profiles', 'clients', 'cases', 'stages', 'sessions', 'admin_tasks', 'appointments', 'accounting_entries', 'assistants', 'invoices', 'invoice_items', 'case_documents', 'sync_deletions'];
BEGIN
    FOR tbl IN SELECT unnest(tables) LOOP
        BEGIN
            EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.' || tbl;
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
    END LOOP;
END $$;
`;

interface ConfigurationModalProps {
    onRetry: () => void;
}

const ConfigurationModal: React.FC<ConfigurationModalProps> = ({ onRetry }) => {
    return (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-[200]">
            <div className="bg-white p-6 rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col">
                <div className="flex items-center gap-3 mb-4 text-amber-600">
                    <ServerIcon className="w-8 h-8" />
                    <h2 className="text-2xl font-bold">إعداد قاعدة البيانات للمزامنة</h2>
                </div>
                
                <div className="overflow-y-auto flex-grow pr-2">
                    <div className="bg-blue-50 border-s-4 border-blue-500 p-4 mb-4 rounded">
                        <div className="flex">
                            <div className="flex-shrink-0"><ExclamationTriangleIcon className="h-5 w-5 text-blue-400" /></div>
                            <div className="ms-3">
                                <p className="text-sm text-blue-700">تنبيه: إذا كنت تواجه مشكلة في المزامنة، يرجى تشغيل الكود أدناه في SQL Editor الخاص بـ Supabase.</p>
                            </div>
                        </div>
                    </div>

                    <div className="bg-gray-50 p-3 rounded-lg border border-gray-200 mb-4">
                        <div className="flex justify-between items-center mb-2">
                            <strong className="text-gray-900">كود الإصلاح:</strong>
                            <CopyButton textToCopy={unifiedScript} />
                        </div>
                        <pre className="bg-gray-800 text-green-400 p-3 rounded overflow-x-auto text-xs font-mono h-48" dir="ltr">{unifiedScript}</pre>
                    </div>
                </div>

                <div className="mt-6 flex justify-end pt-4 border-t">
                    <button onClick={onRetry} className="px-6 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700">إعادة المحاولة</button>
                </div>
            </div>
        </div>
    );
};

export default ConfigurationModal;
